pipeline:
    build:
        image: node:${NODE_VERSION}
        commands:
            - node -v
            - cp test/config.js.sample test/config.js
            - npm install -d
            - npm install mongoose@${MONGOOSE_VERSION}
            - npm test

services:
    mongo:
        image: mongo:latest

matrix:
    NODE_VERSION:
        - 4
        - 6
        - 7
    MONGOOSE_VERSION:
        - 4.6.x
        - 4.7.x
