build:
    image: "node:$$NODE_VERSION"
    commands:
        - echo $NODE_VERSION
        - node -v
        - mkdir -p /tmp/npm
        - cp test/config.js.sample test/config.js
        - npm config set cache /tmp/npm
        - npm install -d
        - npm install mongoose@$$MONGOOSE_VERSION
        - npm test
    cache:
        - /tmp/npm

compose:
    mongo:
        image: mongo:latest

matrix:
    NODE_VERSION:
        - 4
        - 5
        - 6
    MONGOOSE_VERSION:
        - 3.6.x
        - 3.8.x
        - 4.0.x
        - 4.2.x
        - 4.4.x
        - 4.6.x
        - 4.7.x

notify:
    email:
        from: $$EMAIL_FROM
        host: $$SMTP_HOST
        port: $$SMTP_PORT
        username: $$SMTP_USERNAME
        password: $$SMTP_PASSWORD
        skip_verify: $$SMTP_SKIP_SSL_VERIFY
        when:
            success: false
            failure: true
