image: node:0.10
services:
    - mongo:latest

before_script:
    - mkdir -p /tmp/npm
    - sed s/localhost/$MONGO_PORT_27017_TCP_ADDR/ test/config.js.sample > test/config.js
    - npm config set cache /tmp/npm
    - npm install -d

spec:3.6:
    stage: test
    script:
        - npm install mongoose@3.6.x
        - npm test
    cache:
        paths:
            - /tmp/npm

spec:3.8:
    stage: test
    script:
        - npm install -d
        - npm install mongoose@3.8.x
        - npm test
    cache:
        paths:
            - /tmp/npm

spec:4.0:
    stage: test
    script:
        - npm install -d
        - npm install mongoose@4.0.x
        - npm test
    cache:
        paths:
            - /tmp/npm
